# Generated by Django 3.1.5 on 2021-01-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('one', 'One'), ('two', 'Two'), ('three', 'Three')], default='one', max_length=20)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Data',
            },
        ),
    ]
