# Generated by Django 3.1.5 on 2021-01-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_is_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_group',
            field=models.CharField(choices=[('one', 'One'), ('two', 'Two'), ('three', 'Three')], default='one', max_length=20),
        ),
    ]
