# Generated by Django 3.1.5 on 2021-01-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_group',
            field=models.CharField(choices=[('one', 'One'), ('two', 'Two'), ('three', 'Three')], max_length=20),
        ),
    ]
